### ISSUE TITLE
"wget" didn't come on my Amazon Linux ECS box

### ISSUE THREAD

**Issue by djsegal** [awslabs/ecs-logs-collector#10]
After ssh'ing into my server, I found out that it didn't come with `wget`.

I had to install it using: 

+ `sudo yum install wget`

------

I was wondering:

+ why my server didn't come with `wget` preinstalled
+ wether that `yum` line should be added to the readme

**Comment by hugoprudente** [comment]
Hi, 

Looking into the pull requests: https://github.com/awslabs/ecs-logs-collector/pull/6 you can see that has a change to use `curl` instead `wget` as optimized instances doesn't provide all common packages to keep it lighter. 

` curl -O https://raw.githubusercontent.com/awslabs/ecs-logs-collector/master/ecs-logs-collector.sh`

**Comment by WillHoule** [comment]
Readme has been updated to reflect the `curl` usage for the script.
