### ISSUE TITLE
script hangs on collecting Docker information

### ISSUE THREAD

**Issue by PepijnK** [awslabs/ecs-logs-collector#13]
Hi,

I'm trying to execute this script on a post-mortem EC2 instance (stopped and started again). It hangs on the line:

`Trying to gather Docker daemon information... `

Here is the full output:

```
[ec2-user@ip-172-31-21-122 ~]$ sudo bash ecs-logs-collector.sh --mode=debug
Trying to check if the script is running as root... ok
Trying to check disk space usage... ok
Trying to collect system information... Amazon Linux AMI release 2016.09
ok
Trying to collect common operating system logs... ok
Trying to get mount points and volume information... ok
Trying to check SELinux status... ok
Trying to get iptables list... ok
Trying to detect installed packages... ok
Trying to detect active system services list... ok
Trying to gather Docker daemon information... 
```
Switching modes doesn't help.

**Comment by WillHoule** [comment]
Hey there!

For that step in the collection, the script uses the builtin Docker commands to gather the information. So this seems like the Docker daemon itself was hanging when receiving commands. If you manually run something like `docker info` or `docker ps` from the instance, are you seeing a delayed/no response?

Regardless, it'd probably be a good idea for a timeout of sorts to be added for some of the collection steps.

**Comment by UnaKarlsen** [comment]
This sort of issue is usually as a result of the Docker Daemon being unresponsive. The Docker client just never seems to time out when requesting info from the daemon.

A possible fix for this would be to ping the Docker API to check whether it is responding first.
  curl  -S -m 60 --unix-socket /var/run/docker.sock http://localhost/_ping
Doing this lets you set a timeout. If the API does not respond successfully, there is no point in running any of the Docker commands as they will just hang. This can be reported to the user and the rest of the log collection can continue as per normal. 

I'll try to send a PR with this modification in the next day or 2.
