### ISSUE TITLE
Creates wrong archive type

### ISSUE THREAD

**Issue by treaves** [awslabs/ecs-logs-collector#16]
This may be a minor issue, but, this script produces a tgz, which can not be uploaded to GitHub.  So the user has to uncompress and create a zip file.

**Comment by jhaynes** [comment]
Hi @treaves sorry for the incredibly slow response. 

The script currently produces a `.tgz` file which GitHub doesn't allow. However, that is shorthand for `.tar.gz` which is the more proper name and GitHub does allow. Would changing the name to the long version be acceptable? 

That said, be cautious uploading the tar file this script creates. While we are careful to avoid logging any sensitive information like passwords, some companies may consider portions of the information confidential.

**Comment by shatil** [comment]
+1 please change to widely-accepted `*.tar.gz`.

**Comment by jahkeup** [comment]
To reiterate what @jhaynes mentioned, it's imperative that the user does not upload the resulting archive without acknowledging that what they're uploading will be publicly accessible regardless of its contents once its on Github. A very loud warning message should (must?) accompany this change.
