### ISSUE TITLE
Detect required tools and optionally install if missing

### ISSUE THREAD

**Issue by jahkeup** [awslabs/ecs-logs-collector#35]
### Summary

Command line tools required by this script are checked at the time of the invocation, it would be more fitting to check their presence at the beginning and either notify the user what is missing and optionally offer to install them. Additional checks for certain functionalities (flag support, rudimentary version requirements) may be added based on usages but not necessary for consideration with this issue.

**Comment by mythri-garaga** [comment]
Closing this issue as it was created by ECS Agent devs and don't have any customer +1s.
