### ISSUE TITLE
Feature Request: dmesg logs Human Readable timestamps

### ISSUE THREAD

**Issue by akshitkh** [awslabs/ecs-logs-collector#37]
### Summary

The dmesg logs can be collected with Human readable timestamps with a simple flag. "-T"

### Description

 In the "get_kernel_logs()" function, change "dmesg" to "dmesg -T"

**Comment by jahkeup** [comment]
Hi @mallocator4, that's a great idea! If you'd like to make the change yourself, please feel free to open a Pull Request with your suggested change and we'll review it for inclusion. Thanks!

**Comment by jahkeup** [comment]
Fixed with #39
