### ISSUE TITLE
Update log collector to work with AL2 (and other systemd based things)

### ISSUE THREAD

**Issue by jhaynes** [awslabs/ecs-logs-collector#40]
### Summary
The logs collector today is focused on Amazon Linux 1. However, Amazon Linux 2 is systemd based which means log collection should happen via journald rather than via `/var/log/`.

**Comment by jahkeup** [comment]
Some work has been done in #47, but I think we're missing some surface area that can better accommodate AL2 based AMIs.

**Comment by yhlee-aws** [comment]
https://github.com/awslabs/ecs-logs-collector/pull/49 implemented better support for AL2 and other platforms. Resolving.
