### ISSUE TITLE
Script didnt generate tarball.. 

### ISSUE THREAD

**Issue by chakri78** [awslabs/ecs-logs-collector#42]
### Summary
ecs-logs-collector script did not create tarball. 

### Description
Script Documentation details require update with right tarball location. 

### Expected Behavior
collect.tgz file is exepcted in the path where script is executed. 
### Observed Behavior

tarball with instancename.tgz is observed in collect folder. 

Below are additional details.. 

Trying to collect Docker daemon logs ... ok
Trying to collect Amazon ECS Container Agent logs ... ok
Trying to collect Amazon ECS Container Agent state and config ... ok
Trying to collect Amazon ECS Container Agent engine data ... ok
Trying to collect Amazon ECS init logs ... ok
Trying to check if the script is running as root ... ok
Trying to resolve instance-id ... ecs-logs-collector.sh: line 175: ./collect/i-0cf25496945da6295/i-0cf25496945da6295/system/instance-id.txt: No such file or directory
ok
Trying to collect system information ... ok
Trying to enable debug mode for the Docker daemon ... Trying to restart Docker daemon to enable debug mode ... Stopping docker:                              [  OK  ]
Starting docker:	.                                  [  OK  ]
ok
Trying to enable debug mode for the Amazon ECS Container Agent ... Trying to restart the Amazon ECS Container Agent to enable debug mode ... stop: Job has already been stopped: ecs
ecs start/running, process 3087
ok
Trying to archive gathered log information ... ok
# ls
collect  ecs-logs-collector.sh

The script is generating tarball with instance id in the collect folder. Please update the Documentation page. 

Trying to archive gathered log information ... + local tar_bin
++ which tar
+ tar_bin=/bin/tar
+ '[' -z /bin/tar ']'
+ cd .
+ /bin/tar -czf ./collect/i-0cf25496945da6295.tgz ./collect/i-0cf25496945da6295
+ ok
+ echo ok

**Comment by jahkeup** [comment]
Hi @chakri78, to be clear, are you saying that you observed the script successfully collecting the diagnostic information, but it placing it at `./collect/i-0cf25496945da6295.tgz` instead of `collect.tgz` (which is what's in the README)?

If this is the case, we'll at the very least update the README to indicate the correct location. Additionally, I think it would also be worth prefixing the resulting tarball with `collect` (eg: `collect-i-0cf25496945da6295.tgz`), what are your thoughts on that?

**Comment by jahkeup** [comment]
The tarball is now dropped adjacent to where you run the log collector from:

```
[root@ip-172-31-35-155 tmp]# ls -al | grep collect
drwxr-xr-x  3 root     root       4096 Nov 13 18:15 collect
-rw-r--r--  1 root     root     396298 Nov 13 18:15 collect-i-018ed2abc705b4e4e.tgz
-rwxr-xr-x  1 ec2-user ec2-user  16797 Nov 13 18:15 ecs-logs-collector.sh
```
