### ISSUE TITLE
Consider collecting aws-appmesh.log

### ISSUE THREAD

**Issue by dkeightley** [awslabs/ecs-logs-collector#52]
The recent App Mesh CNI integration with proxyConfiguration logs to /var/log/ecs/aws-appmesh.log.yyy-mm-dd-hh

Raising this to create awareness and determine if this is useful to collect in the ecs-logs-collector

**Comment by fjromerom** [comment]
We collect all the files stored in the folder /var/log/ecs.

https://github.com/awslabs/ecs-logs-collector/blob/master/ecs-logs-collector.sh#L373
