### ISSUE TITLE
[Feature Request] Collect GPU Info for GPU Container Instances

### ISSUE THREAD

**Issue by rohanmangal** [awslabs/ecs-logs-collector#73]
### Summary
Added a routine to collect GPU details for GPU Container Instances

### Description
Currently script doesn't collects GPU related information GPU Container Instances, this change will add output of:
1. nvidia-smi -L listing GPUs
2. nvidia-smi -q Details of all GPUs

**Comment by Realmonia** [comment]
Fixed by https://github.com/aws/amazon-ecs-logs-collector/pull/74 change merged. Thanks for the contribution!
